name: flutterconfig_cli
description: FlutterConfig CLI to help with configurations in your applications.
version: 0.0.1
homepage: https://docs.page/Mastersam07/flutterconfig_cli
repository: https://github.com/mastersam07/flutterconfig

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.4.1
  cli_completion: ^0.3.0
  mason_logger: ^0.2.5
  pub_updater: ^0.3.1
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.4
  build_verify: ^3.1.0
  build_version: ^2.1.1
  lints: ^2.1.1
  mocktail: ^1.0.0
  test: ^1.24.6

executables:
  flutterconfig:
